---

- name: setup conf/* rewrite files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/httpd/conf/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - now.rewrites
  notify: reload httpd

- name: register/start httpd service
  ansible.builtin.service:
    name: httpd
    enabled: True
    state: started
  when: not is_baking_ami
