---

- name: setup conf/* rewrite files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/httpd/conf/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - now.rewrites
  register: wh_conf_files

- name: trigger reload httpd
  debug:
    msg: trigger reload httpd
  changed_when: wh_conf_files.changed
  notify: reload httpd
  when: not is_baking_ami

- name: register/start httpd service
  ansible.builtin.service:
    name: httpd
    enabled: True
    state: started
  when: not is_baking_ami
