---

- name: install nginx repo
  ansible.builtin.yum_repository:
    name: nginx
    description: Nginx - $basearch
    baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: False
    enabled: False

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
    disablerepo: "*"
    enablerepo: nginx

- name: setup nginx/nginx.conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0640

- name: remove common conf.d/files
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/{{ item }}"
    state: absent
  loop:
    - default.conf
