
- name: setup jq
  get_url:
    dest: /usr/bin/jq
    url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    owner: root
    group: root
    mode: 0755
  register: setup_jq
  until: setup_jq is success
  retries: 5
  delay: 5
