---

- name: install httpd 2.4
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: remove common conf.d/files
  ansible.builtin.file:
    path: "/etc/httpd/conf.d/{{ item }}"
    state: absent
  loop:
    - autoindex.conf
    - README
    - userdir.conf
    - welcome.conf

- name: setup logrotate.d/httpd
  ansible.builtin.template:
    src: logrotate_httpd
    dest: /etc/logrotate.d/httpd
    owner: root
    group: root
    mode: 0644

- name: install mod_ssl
  ansible.builtin.dnf:
    name: mod_ssl
    state: present
  when: apache_mod_ssl | default(False)

- name: create dummy ssl vhost file
  ansible.builtin.copy:
    content: "# {{ config_managed }}"
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  when: apache_mod_ssl | default(False)

- name: setup httpd/*/html directories for vhosts
  ansible.builtin.file:
    path: "/home/httpd/{{ item.servername }}/html"
    state: directory
    owner: apache
    group: apache
    mode: 0775
  loop: "{{ apache_vhosts | default([]) }}"

- name: setup httpd/*/html root directories for vhosts
  ansible.builtin.file:
    path: "/home/httpd/{{ item.servername }}/html"
    state: directory
    owner: apache
    group: apache
    mode: 0775
  loop: "{{ apache_vhosts | default([]) }}"

- name: create html/status.html files for vhosts
  ansible.builtin.copy:
    content: "{{ item.servername }} server available"
    dest: "/home/httpd/{{ item.servername }}/html/status.html"
    owner: apache
    group: apache
    mode: 0644
  loop: "{{ apache_vhosts | default([]) }}"

- name: setup httpd/* log directories for vhosts
  ansible.builtin.file:
    path: "/var/log/httpd/{{ item.servername }}"
    state: directory
    owner: apache
    group: apache
    mode: 0775
  loop: "{{ apache_vhosts | default([]) }}"

- name: setup conf/* config/rewrite files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/httpd/conf/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - httpd.conf
    - security.rewrites
  register: apache_conf_files

- name: setup conf.d/* config files for vhosts
  ansible.builtin.template:
    src: vhost.conf
    dest: "/etc/httpd/conf.d/{{ item.prefix | default('') }}{{ item.servername }}.conf"
    owner: apache
    group: apache
    mode: 0644
  loop: "{{ apache_vhosts | default([]) }}"
  register: apache_confd_files

- name: trigger reload httpd
  debug:
    msg: trigger reload httpd
  changed_when: apache_conf_files.changed or apache_confd_files.changed
  notify: reload httpd
  when: not is_baking_ami
