---

- name: setup ansible group
  ansible.builtin.group:
    name: ansible
    state: present
    gid: 7000

- name: setup ansible user
  ansible.builtin.user:
    name: ansible
    uid: 7000
    group: ansible
    state: present

- name: setup sudoers.d/ansible
  ansible.builtin.template:
    src: sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0640
