---

- name: install mlocate
  ansible.builtin.dnf:
    name: mlocate
    state: present

- name: setup etc/updatedb.conf
  ansible.builtin.template:
    src: updatedb.conf
    dest: /etc/updatedb.conf
    owner: root
    group: root
    mode: 0644
