---

- name: Add CP group
  ansible.builtin.group:
    name: cp
    state: present
    gid: 22222

- name: Add CP user
  ansible.builtin.user:
    name: cp
    state: present
    uid: 22222
    group: cp

- name: Create prometheus dir
  ansible.builtin.file:
    path: /mnt/prometheus
    state: directory
    owner: nobody
    group: nobody
    mode: 0755

- name: Create grafana dir
  ansible.builtin.file:
    path: /mnt/grafana
    state: directory
    owner: nobody
    group: nobody
    mode: 0755
