---

- name: setup role group
  ansible.builtin.add_host:
    name: localhost
    groups:
      - "{{ extravar_role }}"
  changed_when: False

- name: output role stanza
  ansible.builtin.debug:
    msg: "{{ groupvar_role_output }}"

- name: setup env group
  ansible.builtin.add_host:
    name: localhost
    groups:
      - "{{ extravar_env }}"
  changed_when: False

- name: output env stanza
  ansible.builtin.debug:
    msg: "{{ groupvar_env_output }}"

- name: setup is_bootstrapping var
  ansible.builtin.set_fact:
    is_bootstrapping: "{{ True if 'yes' == extravar_bootstrapping | default('no') else False }}"
