---

- name: setup conf/* rewrite files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/httpd/conf/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - secure.rewrites
  register: ws_conf_files

- block:
    - name: get hello-app services
      ansible.builtin.uri:
        url: http://localhost:4646/v1/service/hello-app
        return_content: True
      register: hello_app_services

    - name: show hello-app services
      debug:
        var: hello_app_services
  ignore_errors: True

- name: trigger reload httpd
  debug:
    msg: trigger reload httpd
  changed_when: ws_conf_files.changed
  notify: reload httpd
  when: not is_baking_ami

- name: register/start httpd service
  ansible.builtin.service:
    name: httpd
    enabled: True
    state: started
  when: not is_baking_ami
