---

- shell:
    cmd: |
      yum-config-manager \
      --add-repo \
      https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- ansible.builtin.dnf:
    name: docker-ce
    state: present

- ansible.builtin.service:
    name: docker
    state: started
