---

- ansible.builtin.import_playbook: pre_common.yml

- hosts: localhost
  connection: local
  vars_files:
    - tmp/ps_vars.yml
  any_errors_fatal: True
  become: True
  roles:
    - role: roles/resource/common
    - role: roles/app

- ansible.builtin.import_playbook: post_common.yml
