---

- hosts: localhost
  connection: local
  become: True
  roles:
  - role: roles/assert
  - role: roles/setup
  - role: roles/yum
  - role: roles/netcat
  - role: roles/cpan
  # - role: roles/nomad
