---

- ansible.builtin.import_playbook: pre_common.yml

- hosts: localhost
  connection: local
  any_errors_fatal: True
  become: True
  roles:
    - role: roles/resource/common
    - role: roles/resource/ps_vars
    - role: roles/resource/httpd_2_4_bare

- ansible.builtin.import_playbook: post_common.yml
