---

- hosts: localhost
  connection: local
  vars_files:
    - tmp/ps_vars.yml
  any_errors_fatal: True
  become: True
  roles:
    - role: roles/action/assert
    - role: roles/action/setup
    - role: roles/resource/common
    - role: roles/resource/dnf
    - role: roles/resource/development_tools
    - role: roles/resource/netcat
    - role: roles/resource/cpan
    - role: roles/resource/tree
    - role: roles/resource/jq
    - role: roles/resource/mlocate
    - role: roles/resource/bash
    - role: roles/resource/git
