---

- ansible.builtin.import_playbook: pre_common.yml

- hosts: localhost
  connection: local
  become: True
  roles:
    - role: roles/resource/httpd_2_4

- ansible.builtin.import_playbook: post_common.yml
