---

- name: setup nomad group
  ansible.builtin.group:
    name: nomad
    state: present
    gid: 5000

- name: setup nomad user
  ansible.builtin.user:
    name: nomad
    uid: 5000
    group: nomad
    state: present

- name: install hashicorp repo
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: True
    enabled: False

- name: install nomad
  ansible.builtin.dnf:
    name: nomad
    state: present
    disablerepo: "*"
    enablerepo: hashicorp

- name: install nomad autocomplete
  shell: |
    nomad -autocomplete-install
  when: is_baking_ami
  ignore_errors: True

- name: remove nomad.d/files
  ansible.builtin.file:
    path: "/etc/nomad.d/{{ item }}"
    state: absent
  loop:
    - nomad.env
    - nomad.hcl
  when: is_baking_ami

- name: setup nomad/* data directories
  ansible.builtin.file:
    path: "/opt/nomad/{{ item }}"
    state: directory
    owner: nomad
    group: nomad
    mode: 0775
  loop:
    - server
    - alloc
    - client
    - plugins
    - data

- name: chown -R /opt/nomad dirs/files
  ansible.builtin.file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad
    recurse: True
  when: is_baking_ami

- name: setup log/nomad.log
  ansible.builtin.file:
    path: /var/log/nomad.log
    state: touch
    owner: nomad
    group: nomad
    mode: 0644
  when: is_baking_ami

- name: setup sudoers.d/nomad
  ansible.builtin.template:
    src: sudoers_nomad
    dest: /etc/sudoers.d/nomad
    owner: root
    group: root
    mode: 0640

- name: setup system/nomad.service
  ansible.builtin.template:
    src: nomad.service
    dest: /usr/lib/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  register: nomad_nomadservice_file

- name: force systemd reload when service file changes
  ansible.builtin.systemd:
    daemon_reload: True
  changed_when: nomad_nomadservice_file.changed
  when: nomad_nomadservice_file.changed

- name: setup nomad.d/nomad.hcl file
  ansible.builtin.template:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: 0644
  register: nomad_nomadhcl_file

- name: trigger restart nomad
  debug:
    msg: trigger restart nomad
  changed_when: nomad_nomadhcl_file.changed or nomad_nomadservice_file.changed
  notify: restart nomad
  when: not is_baking_ami

- name: register/start nomad service
  ansible.builtin.service:
    name: nomad
    enabled: True
    state: started
  when: not is_baking_ami
